/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ingreso;

import javax.swing.ImageIcon;

/**
 *
 * @author asus
 */
public class Register extends javax.swing.JFrame {
    private final ImageIcon ICONO = new ImageIcon(getClass().getResource("/png/user.png"));

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(null);
        imagen.setIcon(new ImageIcon(ICONO.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(),0)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloRegister = new javax.swing.JLabel();
        tituloNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        tituloApellido = new javax.swing.JLabel();
        textApellido = new javax.swing.JPasswordField();
        tituloContraseña = new javax.swing.JLabel();
        textContraseña = new javax.swing.JPasswordField();
        tituloConfirmarContraseña = new javax.swing.JLabel();
        textConfirmarContraseña = new javax.swing.JPasswordField();
        tituloCorreo = new javax.swing.JLabel();
        textCorreo = new javax.swing.JPasswordField();
        botonLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tituloBienvenido = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tituloRegister.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        tituloRegister.setForeground(new java.awt.Color(255, 255, 255));
        tituloRegister.setText("Registrarse");

        tituloNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloNombre.setForeground(new java.awt.Color(255, 255, 255));
        tituloNombre.setText("Nombre");

        textNombre.setBackground(new java.awt.Color(0, 0, 0));
        textNombre.setForeground(new java.awt.Color(255, 255, 255));
        textNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        tituloApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloApellido.setForeground(new java.awt.Color(255, 255, 255));
        tituloApellido.setText("Apellido");

        textApellido.setBackground(new java.awt.Color(0, 0, 0));
        textApellido.setForeground(new java.awt.Color(255, 255, 255));
        textApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        tituloContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloContraseña.setForeground(new java.awt.Color(255, 255, 255));
        tituloContraseña.setText("Contraseña");

        textContraseña.setBackground(new java.awt.Color(0, 0, 0));
        textContraseña.setForeground(new java.awt.Color(255, 255, 255));
        textContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        tituloConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        tituloConfirmarContraseña.setText("Confirmar Contraseña");

        textConfirmarContraseña.setBackground(new java.awt.Color(0, 0, 0));
        textConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        textConfirmarContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        tituloCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloCorreo.setForeground(new java.awt.Color(255, 255, 255));
        tituloCorreo.setText("Correo electronico");

        textCorreo.setBackground(new java.awt.Color(0, 0, 0));
        textCorreo.setForeground(new java.awt.Color(255, 255, 255));
        textCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        botonLogin.setBackground(new java.awt.Color(102, 102, 255));
        botonLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonLogin.setForeground(new java.awt.Color(255, 255, 255));
        botonLogin.setText("REGISTRARSE");
        botonLogin.setAutoscrolls(true);
        botonLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        botonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(tituloRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tituloCorreo)
                            .addComponent(tituloApellido)
                            .addComponent(tituloNombre)
                            .addComponent(tituloContraseña)
                            .addComponent(tituloConfirmarContraseña)
                            .addComponent(textNombre)
                            .addComponent(textApellido)
                            .addComponent(textContraseña)
                            .addComponent(textConfirmarContraseña)
                            .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tituloRegister)
                .addGap(18, 18, 18)
                .addComponent(tituloNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tituloCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tituloConfirmarContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        tituloBienvenido.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        tituloBienvenido.setText("Bienvenido");

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/autos2.png"))); // NOI18N
        imagen.setAlignmentX(0.5F);
        imagen.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        imagen.setIconTextGap(0);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(tituloBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        
    }//GEN-LAST:event_botonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLogin;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField textApellido;
    private javax.swing.JPasswordField textConfirmarContraseña;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JPasswordField textCorreo;
    private javax.swing.JTextField textNombre;
    private javax.swing.JLabel tituloApellido;
    private javax.swing.JLabel tituloBienvenido;
    private javax.swing.JLabel tituloConfirmarContraseña;
    private javax.swing.JLabel tituloContraseña;
    private javax.swing.JLabel tituloCorreo;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel tituloRegister;
    // End of variables declaration//GEN-END:variables
}
